mod.id = "faststats-fabric"
mod.group = "io.github.projectunified"
mod.version = "0.2.0"

deps.fabric_loader = "0.19.2"
loomx.loom_version = "1.16-SNAPSHOT"

deps.faststats = "0.5.0"

["1.21.11"]
mod.mc_compat = "1.21.11"
mod.mc_releases = ["1.21.11"]

["26.1"]
mod.mc_compat = "~26.1"
mod.mc_releases = ["26.1", "26.1.1"]

["26.2"]
mod.mc_compat = "~26.2"
mod.mc_releases = ["26.2"]